-- One row per team per game, with tidy names and a few derived flags.
select
    game_id,
    team_id,
    team_abbreviation,
    team_name,
    game_date,
    season,
    season || '-' || right((season + 1)::text, 2) as season_label,
    season_type,
    (season_type = 'Playoffs') as is_playoffs,
    matchup,
    -- "OKC vs. HOU" is a home game, "HOU @ OKC" is away
    (matchup like '%vs.%') as is_home,
    split_part(matchup, ' ', 3) as opponent_abbreviation,
    (wl = 'W') as is_win,
    min as minutes_played,
    pts,
    reb,
    oreb,
    dreb,
    ast,
    stl,
    blk,
    tov,
    pf,
    fgm,
    fga,
    fg_pct,
    fg3m,
    fg3a,
    fg3_pct,
    ftm,
    fta,
    ft_pct,
    plus_minus
from {{ source('raw', 'team_game_logs') }}
